import Head from 'next/head'
import Image from 'next/image'
import Hero from '../components/Hero'
import Navbar from '../components/Navbar'
import { SliderData } from '../components/SliderData'
import Slider from '../components/Slider'
import Instagram from '../components/Instagram'




export default function Home() {
  return (
    <div >
      <Head>
        <title>Capture App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Hero heading='Capture Photography' message='Capture Beautiful Moments through lenses'/>
      <Slider slides={SliderData}/>
      <Instagram />
      
    </div>
  )
}
